### ISSUE TITLE
typescript class: must be an object/array

### ISSUE THREAD

**Issue by joelcho** [DawnImpulse/json-keys-sort#1]
### Env

runner: [ts-node](https://www.npmjs.com/package/ts-node)
typescript: [v3.8.3](https://www.npmjs.com/package/typescript/v/3.8.3)

### Code example
```ts
import jssfy from 'json-keys-sort'

let unknown = {
    name:'unknown',
    age:1024,
    isSenior:false
}
console.log('typeof(unknown):', typeof(unknown))

const unknown_sorted = jssfy.sort(unknown)
console.log('sorted:', unknown_sorted)

console.log('json:', JSON.stringify(unknown_sorted))

console.log('----------------------------------------------------------------------')

class User {
    name: string
    age:number
    isSenior: boolean

    constructor(name: string, age:number, isSenior:boolean) {
        this.name = name
        this.age = age
        this.isSenior = isSenior
    }
}

const user = new User('unknown', 1024, false)
console.log('typeof(user):', typeof(user))

const user_sorted = jssfy.sort(user)
console.log('sorted:', user_sorted)

console.log('JSON:', JSON.stringify(user_sorted))
```

### Outputs
```
typeof(unknown): object
sorted: { age: 1024, isSenior: false, name: 'unknown' }
json: {"age":1024,"isSenior":false,"name":"unknown"}
----------------------------------------------------------------------
typeof(user): object

throw new Error("must be an object/array")
```

**Comment by DawnImpulse** [comment]
I am so so sry that I forgot to reply you back (won't happen ever again)

Back to your question, the json-keys-sort package now take into consideration that the input must be either a valid JSON object or JSON array. 

A class though is a valid js object but not a valid JSON object. You have to convert it into an JSON to use. 

```
JSON.parse(JSON.stringify(yourClass))
```

For any urgent inquiries, you can contact me directly on either my Twitter or Email (links in repo readme)

**Comment by joelcho** [comment]
Thank you for your reply, it's resolved

**Comment by joelcho** [comment]
> I am so so sry that I forgot to reply you back (won't happen ever again)
> 
> Back to your question, the json-keys-sort package now take into consideration that the input must be either a valid JSON object or JSON array.
> 
> A class though is a valid js object but not a valid JSON object. You have to convert it into an JSON to use.
> 
> ```
> JSON.parse(JSON.stringify(yourClass))
> ```
> 
> For any urgent inquiries, you can contact me directly on either my Twitter or Email (links in repo readme)

Thank you for your reply, it's resolved
